# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import os

class TestAddrequiremnet():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addrequiremnet(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1338, 692)
    
    # Click Log In and fill credentials
    WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Log In"))
    ).click()
    
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "email"))
    ).send_keys("amalbabu1080@gmail.com")
    
    password_elem = self.driver.find_element(By.NAME, "password")
    password_elem.send_keys("Amalbabu123")
    password_elem.send_keys(Keys.ENTER)
    
    # Wait for dashboard page and sidebar link to load
    create_req_btn = WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.ID, "org-sidebar-create-req"))
    )
    create_req_btn.click()
    
    # Fill requirement form fields
    title_field = WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.ID, "title"))
    )
    title_field.clear()
    title_field.send_keys("Medical Items for senior citizens")
    
    dropdown = self.driver.find_element(By.ID, "beneficiaryType")
    dropdown.find_element(By.XPATH, "//option[. = 'Senior Citizens']").click()
    
    self.driver.find_element(By.ID, "beneficiaryCount").clear()
    self.driver.find_element(By.ID, "beneficiaryCount").send_keys("65")
    
    self.driver.find_element(By.ID, "quantity").clear()
    self.driver.find_element(By.ID, "quantity").send_keys("56")
    
    unit_dropdown = self.driver.find_element(By.ID, "unit")
    unit_dropdown.find_element(By.XPATH, "//option[. = 'Sets']").click()
    
    self.driver.find_element(By.ID, "requiredBefore").send_keys("2026-10-01")
    
    self.driver.find_element(By.ID, "description").clear()
    self.driver.find_element(By.ID, "description").send_keys("monthly medical citizens")
    
    # Upload image file
    image_path = os.path.abspath("sample_test_image.png")
    file_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    file_input.send_keys(image_path)
    
    # Click publish requirement
    publish_btn = WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.ID, "publish-requirement-btn"))
    )
    publish_btn.click()
  
