# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import os

class TestDonation():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_donation(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1338, 692)
    
    # 1. Click Log In
    WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Log In"))
    ).click()
    
    # 2. Fill credentials
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "email"))
    ).send_keys("amalbabu2027@mca.ajce.in")
    
    password_elem = self.driver.find_element(By.NAME, "password")
    password_elem.clear()
    password_elem.send_keys("Amalbabu456")
    
    self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
    
    # 3. Wait for Donor Dashboard & click Browse Requirements link in sidebar
    browse_btn = WebDriverWait(self.driver, 15).until(
        expected_conditions.element_to_be_clickable((By.ID, "sidebar-browse"))
    )
    browse_btn.click()
    
    # 4. Wait for Browse Requirements page and click "Donate Now" on first requirement card
    donate_btn = WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.XPATH, "//button[contains(., 'Donate Now')]"))
    )
    donate_btn.click()
    
    # 5. Fill donation quantity and notes
    quantity_input = WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.ID, "quantity"))
    )
    quantity_input.clear()
    quantity_input.send_keys("10")
    
    unit_dropdown = self.driver.find_element(By.ID, "unit")
    unit_dropdown.find_element(By.XPATH, "//option[. = 'Packets']").click()
    
    notes_input = self.driver.find_element(By.ID, "notes")
    notes_input.clear()
    notes_input.send_keys("here")
    
    # 6. Upload image file
    image_path = os.path.abspath("sample_test_image.png")
    file_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    file_input.send_keys(image_path)
    
    # 7. Submit pledge
    submit_btn = WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']"))
    )
    submit_btn.click()

  
