# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup(self):
    self.driver.maximize_window()
    self.driver.get("http://localhost:3000/signup")
    
    wait = WebDriverWait(self.driver, 10)
    full_name_input = wait.until(expected_conditions.visibility_of_element_located((By.NAME, "fullName")))
    full_name_input.click()
    full_name_input.send_keys("Amal Babu")
    
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("a4amal2003@gmail.com")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("9888987877")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Amalbabu123")
    self.driver.find_element(By.NAME, "confirmPassword").click()
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("Amalbabu123")
    
    terms_checkbox = wait.until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".terms-label > span")))
    terms_checkbox.click()
    
    submit_btn = wait.until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".submit-btn")))
    submit_btn.click()
  
